version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_smi
    ports:
      - "27017:27017"
    extra_hosts:
      "host.docker.internal": host-gateway
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: smi_root
      MONGO_INITDB_ROOT_PASSWORD: f42d699ffe20204ec97387ce592aaca6
      MONGO_INITDB_DATABASE: smi_engineering
      MONGODB_USER: smi_user
      MONGODB_DATABASE: smi_engineering
      MONGODB_PASS: f42d699ffe20204ec97387ce592aaca6

volumes:
  mongodb_data: