version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: smi_root
      MONGO_INITDB_ROOT_PASSWORD: f42d699ffe20204ec97387ce592aaca6
      MONGO_INITDB_DATABASE: smi_engineering

volumes:
  mongodb_data: